version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=Matematika0008034411
      - MYSQL_DATABASE=VSA_PR1
      - MYSQL_USER=vsa
      - MYSQL_PASSWORD=vsa
  springboot-docker-container:
    image: spring-boot-docker
    container_name: springboot-docker-container
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone